const CODE_MAP: Record<string, string> = {
  'Mexico':               'mx',
  'South Africa':         'za',
  'South Korea':          'kr',
  'Tjeckien':             'cz',
  'Canada':               'ca',
  'Bosnien-Hercegovina':  'ba',
  'Qatar':                'qa',
  'Schweiz':              'ch',
  'Brasilien':            'br',
  'Marocko':              'ma',
  'Haiti':                'ht',
  'Skottland':            'gb-sct',
  'USA':                  'us',
  'Paraguay':             'py',
  'Australien':           'au',
  'Turkiet':              'tr',
  'Tyskland':             'de',
  'Curaçao':              'cw',
  'Elfenbenskusten':      'ci',
  'Ecuador':              'ec',
  'Nederländerna':        'nl',
  'Japan':                'jp',
  'Tunisien':             'tn',
  'Sverige':              'se',
  'Belgien':              'be',
  'Egypten':              'eg',
  'Iran':                 'ir',
  'Nya Zeeland':          'nz',
  'Spanien':              'es',
  'Kap Verde':            'cv',
  'Saudiarabien':         'sa',
  'Uruguay':              'uy',
  'Frankrike':            'fr',
  'Senegal':              'sn',
  'Irak':                 'iq',
  'Norge':                'no',
  'Argentina':            'ar',
  'Algeriet':             'dz',
  'Österrike':            'at',
  'Jordanien':            'jo',
  'Portugal':             'pt',
  'DR Kongo':             'cd',
  'Uzbekistan':           'uz',
  'Colombia':             'co',
  'England':              'gb-eng',
  'Kroatien':             'hr',
  'Ghana':                'gh',
  'Panama':               'pa',
}

export function getFlagCode(name: string | null | undefined): string {
  if (!name) return ''
  return CODE_MAP[name] ?? ''
}
